version: "3"
services:
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    build:
      context: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector/config.yml:/etc/otel-collector-config.yml
    networks:
      app-network:
    environment:
      SPLUNK_ACCESS_TOKEN: ${SPLUNK_ACCESS_TOKEN}
      SPLUNK_REALM: ${SPLUNK_REALM}
      SPLUNK_MEMORY_LIMIT_MIB: ${SPLUNK_MEMORY_LIMIT_MIB}
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
